version: "3.8"

services:
    backend:
        image: icu-deterioration-backend
        build:
            context: .
            dockerfile: backend/Dockerfile
        volumes:
            - ./params.yaml:/app/params.yaml
            - ./dvc.yaml:/app/dvc.yaml
        ports: 
            - "8000:8000"
        restart: unless-stopped
        networks: 
            - icu_net

    frontend:
        image: icu-deterioration-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8501:8501"
        depends_on:
            - backend       
        environment:
            - BACKEND_URL=http://backend:8000
        networks:
            - icu_net

networks:
    icu_net:
        driver: bridge
