global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "icu-backend-metrics"
    metrics_path: /metrics
    scheme: https
    
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/token
    
    static_configs:
      - targets:
          - "icu-deterioration-backend-production.up.railway.app"
  