name: Build and Push ML Image

on:
  push:
    branches:
      - main
    paths:
      - "dockerfile"
      - "src/data/**"        
      - "src/entrypoints/**"
      - "src/model/**"
      - "src/config.py"
      - "dvc.yaml"
      - "params.yaml"
      - "requirements.txt"
      - "requirements_heavy.txt"
      - ".github/workflows/ml-image.yaml"

jobs:
  build-ml-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Determine the Image Tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG=dev-${GITHUB_SHA::5}" >> $GITHUB_OUTPUT
          fi 
      
      - name: Build and Push ML Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          push: true
          tags: unstableme02/icu-deterioration-mlops:${{ steps.vars.outputs.TAG }}
        

